// Custom Worker entrypoint: wraps the OpenNext-generated handler so we can
// attach a `scheduled` handler for the Cron Trigger declared in wrangler.jsonc
// (Cloudflare's replacement for vercel.json's cron).
//
// `.open-next/worker.js` is generated by `opennextjs-cloudflare build` and
// doesn't exist in a fresh checkout, so this file is excluded from
// `pnpm typecheck` (see tsconfig.json) — wrangler bundles it independently.
import handler from './.open-next/worker.js';

const worker = {
  fetch: handler.fetch,

  // Fires on the wrangler.jsonc cron schedule. Calls the same refresh route
  // Vercel Cron / the docker sidecar hit, through the self-reference service
  // binding (no public round-trip, no DNS). The route awaits the NWPS refresh
  // and repopulates the shared R2-backed data cache before returning.
  async scheduled(controller, env, ctx) {
    ctx.waitUntil(
      (async () => {
        const res = await env.WORKER_SELF_REFERENCE.fetch(
          // Any host works — service bindings only route on the path.
          'https://self/api/cron/refresh-gauges',
          env.CRON_SECRET
            ? { headers: { Authorization: `Bearer ${env.CRON_SECRET}` } }
            : undefined,
        );
        console.log(`[cron] /api/cron/refresh-gauges -> ${res.status}`);
      })(),
    );
  },
};

export default worker;

// Forward the Durable Object classes the generated worker may define (cache
// queue handlers etc.) so wrangler can still resolve them if enabled later.
export * from './.open-next/worker.js';
